cp resources/ios/icons/icon-small@2x.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-small.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-76@2x.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-76.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-72@2x.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-72.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-60@2x.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-60.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-50@2x.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-50.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-40@2x.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon-40.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon_200.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon@2x.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/icons/icon.png platforms/ios/Bitwallet/Resources/icons/
cp resources/ios/splash/Default-Portrait~ipad.png platforms/ios/Bitwallet/Resources/splash/
cp resources/ios/splash/Default-Portrait@2x~ipad.png platforms/ios/Bitwallet/Resources/splash/
cp resources/ios/splash/Default-Landscape~ipad.png platforms/ios/Bitwallet/Resources/splash/
cp resources/ios/splash/Default-Landscape@2x~ipad.png platforms/ios/Bitwallet/Resources/splash/
cp resources/ios/splash/Default-568h@2x~iphone.png platforms/ios/Bitwallet/Resources/splash/
cp resources/ios/splash/Default~iphone.png platforms/ios/Bitwallet/Resources/splash/
cp resources/ios/splash/Default@2x~iphone.png platforms/ios/Bitwallet/Resources/splash/